version: '2'
services:
  httpd:
    image: reflet/debian8-httpd:1.6
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/virtualhost:/usr/local/apache2/conf.d/virtualhost/
      - web-httpd-log:/usr/local/apache2/logs/
    volumes_from:
      - php
    networks:
      default:
        ipv4_address: 10.0.0.2

  php:
    image: reflet/debian8-php56:1.6
    container_name: 'php'
    command: bash -c 'usermod -o -u ${UID} www-data; groupmod -o -g ${UID} www-data; php-fpm'
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - ./docker/php/xdebug.ini:/usr/local/etc/php.d/xdebug.ini
    extra_hosts:
      - "www.example.com:10.0.0.2"
    networks:
      default:
        ipv4_address: 10.0.0.3

  mysql:
    image: reflet/debian8-mysql55:1.0
    container_name: 'mysql'
    env_file: ./docker/mysql/env
    ports:
      - '3306:3306'
    volumes:
      - web-mysql:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d/
    networks:
      default:
        ipv4_address: 10.0.0.4

  postgres:
    image: reflet/debian8-postgres91:1.1
    container_name: 'postgres'
    env_file: ./docker/postgres/env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d/
      - web-postgres:/var/lib/postgresql/data/
    networks:
      default:
        ipv4_address: 10.0.0.5

  smtp:
    image: schickling/mailcatcher
    container_name: 'smtp'
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      default:
        ipv4_address: 10.0.0.6

  selenium:
    image: selenium/standalone-chrome-debug:latest
    container_name: 'selenium'
    ports:
      - '4444:4444'
      - '5900:5900'
    networks:
      default:
        ipv4_address: 10.0.0.7

volumes:
  web-postgres:
    driver: local
  web-mysql:
    driver: local
  web-httpd-log:
    driver_opts:
      type: none
      device: ${PWD}/logs/
      o: bind

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
