version: '2'
services:
 app:
  image: busybox
  container_name: 'app'
  volumes:
   - ../www:/var/www

 mysql:
  image: reflet/debian8-mysql57:1.1
  container_name: 'mysql'
  env_file: .env.mysql
  ports:
   - '3306:3306'
  volumes:
   - ./initdb.mysql:/docker-entrypoint-initdb.d/
   - mysql-data:/var/lib/mysql

 postgres:
  image: reflet/debian8-postgres96:1.1
  container_name: 'postgres'
  env_file: .env.postgres
  volumes:
   - ./initdb.postgres:/docker-entrypoint-initdb.d/
   - postgres-data:/var/lib/postgresql/data/
  ports:
      - "5432:5432"

 php:
  image: reflet/debian8-php56:1.5
  container_name: 'php'
  ports:
   - '9000:9000'
  volumes:
   - ./php.ini:/usr/local/etc/php/php.ini
   - ./php-ssmtp.conf:/etc/ssmtp/ssmtp.conf
  volumes_from:
   - app
  links:
   - mysql
   - postgres

 httpd:
  image: reflet/debian8-httpd:1.6
  container_name: 'httpd'
  ports:
   - '80:80'
   - '443:443'
  volumes:
   - ./virtualhost:/usr/local/apache2/conf.d/virtualhost/
   - httpd-log:/usr/local/apache2/logs/
  volumes_from:
   - app
  links:
   - php

volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local
  httpd-log:
    driver_opts:
      type: none
      device: /home/vagrant/opt/docker/logs/httpd/
      o: bind

